/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Money } from './money';
 /**
 * 
 *
 * @export
 * @interface AnalyticsInformationDto
 */
export interface AnalyticsInformationDto {

    /**
     * @type {number}
     * @memberof AnalyticsInformationDto
     */
    totalViews: number;

    /**
     * @type {number}
     * @memberof AnalyticsInformationDto
     */
    viewsInWeek: number;

    /**
     * @type {Money}
     * @memberof AnalyticsInformationDto
     */
    revenue: Money;
}
