/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { OptionEntity } from './option-entity';
 /**
 * 
 *
 * @export
 * @interface CategoryEntity
 */
export interface CategoryEntity {

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof CategoryEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof CategoryEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof CategoryEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    name: string;

    /**
     * @type {Array<OptionEntity>}
     * @memberof CategoryEntity
     */
    options: Array<OptionEntity>;

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    gameID?: string;

    /**
     * @type {string}
     * @memberof CategoryEntity
     */
    slug: string;
}
