/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { ChatReadRecord } from './chat-read-record';
import { FileEntity } from './file-entity';
import { MessageEntity } from './message-entity';
import { UserEntity } from './user-entity';
 /**
 * 
 *
 * @export
 * @interface ChatEntity
 */
export interface ChatEntity {

    /**
     * @type {string}
     * @memberof ChatEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof ChatEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof ChatEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof ChatEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof ChatEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof ChatEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof ChatEntity
     */
    name: string;

    /**
     * @type {Array<UserEntity>}
     * @memberof ChatEntity
     */
    participants?: Array<UserEntity> | null;

    /**
     * @type {FileEntity}
     * @memberof ChatEntity
     */
    image?: FileEntity;

    /**
     * @type {boolean}
     * @memberof ChatEntity
     */
    deleted: boolean;

    /**
     * @type {boolean}
     * @memberof ChatEntity
     */
    isVerified: boolean;

    /**
     * @type {Array<ChatReadRecord>}
     * @memberof ChatEntity
     */
    readRecords?: Array<ChatReadRecord> | null;

    /**
     * @type {string}
     * @memberof ChatEntity
     */
    type: ChatEntityTypeEnum;

    /**
     * @type {Array<MessageEntity>}
     * @memberof ChatEntity
     */
    messages?: Array<MessageEntity> | null;

    /**
     * @type {MessageEntity}
     * @memberof ChatEntity
     */
    lastMessage?: MessageEntity;

    /**
     * @type {number}
     * @memberof ChatEntity
     */
    unreadMessages?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatEntityTypeEnum {
    Private = 'Private',
    Support = 'Support'
}

