/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConfirmPurchaseDto
 */
export interface ConfirmPurchaseDto {

    /**
     * @type {string}
     * @memberof ConfirmPurchaseDto
     */
    purchaseId: string;

    /**
     * @type {string}
     * @memberof ConfirmPurchaseDto
     */
    productId: string;

    /**
     * @type {number}
     * @memberof ConfirmPurchaseDto
     */
    rate: number;

    /**
     * @type {string}
     * @memberof ConfirmPurchaseDto
     */
    rateText: string;
}
