/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateFileDto } from './create-file-dto';
 /**
 * 
 *
 * @export
 * @interface CreateGameDto
 */
export interface CreateGameDto {

    /**
     * @type {string}
     * @memberof CreateGameDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateGameDto
     */
    description: string;

    /**
     * @type {string}
     * @memberof CreateGameDto
     */
    type: CreateGameDtoTypeEnum;

    /**
     * @type {Array<string>}
     * @memberof CreateGameDto
     */
    tags: Array<string>;

    /**
     * @type {CreateFileDto}
     * @memberof CreateGameDto
     */
    logo: CreateFileDto;

    /**
     * @type {CreateFileDto}
     * @memberof CreateGameDto
     */
    banner: CreateFileDto;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateGameDtoTypeEnum {
    Game = 'Game',
    Application = 'Application'
}

