/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateOptionDto } from './create-option-dto';
 /**
 * 
 *
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {

    /**
     * @type {string}
     * @memberof CreateCategoryDto
     */
    name: string;

    /**
     * @type {Array<CreateOptionDto>}
     * @memberof CreateCategoryDto
     */
    options?: Array<CreateOptionDto> | null;

    /**
     * @type {string}
     * @memberof CreateCategoryDto
     */
    gameId?: string;
}
