/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateFileDto } from './create-file-dto';
 /**
 * 
 *
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {

    /**
     * @type {string}
     * @memberof CreateProductDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateProductDto
     */
    description: string;

    /**
     * @type {string}
     * @memberof CreateProductDto
     */
    categoryId: string;

    /**
     * @type {string}
     * @memberof CreateProductDto
     */
    gameId: string;

    /**
     * @type {number}
     * @memberof CreateProductDto
     */
    price: number;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof CreateProductDto
     */
    attributes?: { [key: string]: string; } | null;

    /**
     * @type {Array<CreateFileDto>}
     * @memberof CreateProductDto
     */
    images?: Array<CreateFileDto> | null;

    /**
     * @type {Array<string>}
     * @memberof CreateProductDto
     */
    autoAnswers?: Array<string> | null;
}
