/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateNotificationDto
 */
export interface CreateNotificationDto {

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    text: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof CreateNotificationDto
     */
    data: { [key: string]: string; };

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    userId?: string | null;

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    role?: CreateNotificationDtoRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateNotificationDtoRoleEnum {
    Other = 'Other',
    User = 'User',
    Seller = 'Seller',
    Moderator = 'Moderator',
    Admin = 'Admin',
    Owner = 'Owner',
    SuperAdmin = 'SuperAdmin'
}

