/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePurchaseDto
 */
export interface CreatePurchaseDto {

    /**
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    productId: string;

    /**
     * @type {string}
     * @memberof CreatePurchaseDto
     */
    providerName: string;
}
