/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateOptionDto
 */
export interface CreateOptionDto {

    /**
     * @type {string}
     * @memberof CreateOptionDto
     */
    group: string;

    /**
     * @type {string}
     * @memberof CreateOptionDto
     */
    label: string;

    /**
     * @type {string}
     * @memberof CreateOptionDto
     */
    type: CreateOptionDtoTypeEnum;

    /**
     * @type {string}
     * @memberof CreateOptionDto
     */
    value?: string | null;

    /**
     * @type {string}
     * @memberof CreateOptionDto
     */
    field?: string | null;

    /**
     * @type {number}
     * @memberof CreateOptionDto
     */
    sequence?: number;

    /**
     * @type {number}
     * @memberof CreateOptionDto
     */
    valueRangeMin?: number | null;

    /**
     * @type {number}
     * @memberof CreateOptionDto
     */
    valueRangeMax?: number | null;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateOptionDtoTypeEnum {
    Selector = 'Selector',
    Switch = 'Switch',
    Range = 'Range'
}

