/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Stream } from './stream';
 /**
 * 
 *
 * @export
 * @interface CreateFileDto
 */
export interface CreateFileDto {

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    downloadUrl?: string | null;

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    fileId?: string | null;

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    mimeType?: string | null;

    /**
     * @type {Stream}
     * @memberof CreateFileDto
     */
    stream?: Stream;
}
