/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FileEntity
 */
export interface FileEntity {

    /**
     * @type {string}
     * @memberof FileEntity
     */
    id: string;

    /**
     * @type {string}
     * @memberof FileEntity
     */
    fileName: string;

    /**
     * @type {string}
     * @memberof FileEntity
     */
    filePath: string;

    /**
     * @type {string}
     * @memberof FileEntity
     */
    mimeType: string;

    /**
     * @type {number}
     * @memberof FileEntity
     */
    size?: number;
}
