/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { FileEntity } from './file-entity';
import { PurchaseEntity } from './purchase-entity';
import { ReviewEntity } from './review-entity';
import { UserEntity } from './user-entity';
 /**
 * 
 *
 * @export
 * @interface MessageEntity
 */
export interface MessageEntity {

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    id?: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof MessageEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof MessageEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof MessageEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    chatID?: string;

    /**
     * @type {UserEntity}
     * @memberof MessageEntity
     */
    fromUser?: UserEntity;

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    text?: string | null;

    /**
     * @type {string}
     * @memberof MessageEntity
     */
    type?: MessageEntityTypeEnum;

    /**
     * @type {FileEntity}
     * @memberof MessageEntity
     */
    image?: FileEntity;

    /**
     * @type {ReviewEntity}
     * @memberof MessageEntity
     */
    review?: ReviewEntity;

    /**
     * @type {PurchaseEntity}
     * @memberof MessageEntity
     */
    purchase?: PurchaseEntity;
}

/**
 * @export
 * @enum {string}
 */
export enum MessageEntityTypeEnum {
    Text = 'Text',
    Image = 'Image',
    Purchase = 'Purchase',
    Review = 'Review'
}

