/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface NotificationCreatedDto
 */
export interface NotificationCreatedDto {

    /**
     * @type {Array<string>}
     * @memberof NotificationCreatedDto
     */
    userIds: Array<string>;

    /**
     * @type {number}
     * @memberof NotificationCreatedDto
     */
    sentToUsers: number;
}
