/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
 /**
 * 
 *
 * @export
 * @interface OptionEntity
 */
export interface OptionEntity {

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof OptionEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof OptionEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof OptionEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    group: string;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    label: string;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    type: OptionEntityTypeEnum;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    value: string;

    /**
     * @type {string}
     * @memberof OptionEntity
     */
    field: string;

    /**
     * @type {number}
     * @memberof OptionEntity
     */
    sequence: number;

    /**
     * @type {number}
     * @memberof OptionEntity
     */
    valueRangeMin?: number | null;

    /**
     * @type {number}
     * @memberof OptionEntity
     */
    valueRangeMax?: number | null;
}

/**
 * @export
 * @enum {string}
 */
export enum OptionEntityTypeEnum {
    Selector = 'Selector',
    Switch = 'Switch',
    Range = 'Range'
}

