/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
 /**
 * 
 *
 * @export
 * @interface PaymentSystemEntity
 */
export interface PaymentSystemEntity {

    /**
     * @type {string}
     * @memberof PaymentSystemEntity
     */
    id?: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof PaymentSystemEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof PaymentSystemEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof PaymentSystemEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof PaymentSystemEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof PaymentSystemEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof PaymentSystemEntity
     */
    name: string;

    /**
     * @type {boolean}
     * @memberof PaymentSystemEntity
     */
    isActive?: boolean;
}
