/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { Money } from './money';
import { ProductEntity } from './product-entity';
import { TransactionEntity } from './transaction-entity';
import { WalletEntity } from './wallet-entity';
 /**
 * 
 *
 * @export
 * @interface PurchaseEntity
 */
export interface PurchaseEntity {

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof PurchaseEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof PurchaseEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof PurchaseEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    currency: PurchaseEntityCurrencyEnum;

    /**
     * @type {Money}
     * @memberof PurchaseEntity
     */
    amount: Money;

    /**
     * @type {WalletEntity}
     * @memberof PurchaseEntity
     */
    wallet: WalletEntity;

    /**
     * @type {ProductEntity}
     * @memberof PurchaseEntity
     */
    product: ProductEntity;

    /**
     * @type {boolean}
     * @memberof PurchaseEntity
     */
    completed: boolean;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    chatId?: string | null;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    status: PurchaseEntityStatusEnum;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    reviewId?: string | null;

    /**
     * @type {TransactionEntity}
     * @memberof PurchaseEntity
     */
    transaction: TransactionEntity;

    /**
     * @type {string}
     * @memberof PurchaseEntity
     */
    statusDescription?: string | null;
}

/**
 * @export
 * @enum {string}
 */
export enum PurchaseEntityCurrencyEnum {
    RussianRuble = 'RussianRuble',
    Dollar = 'Dollar'
}
/**
 * @export
 * @enum {string}
 */
export enum PurchaseEntityStatusEnum {
    Chatting = 'Chatting',
    Processing = 'Processing',
    Failed = 'Failed',
    Success = 'Success',
    Rejected = 'Rejected',
    Expired = 'Expired'
}

