/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { ProductEntity } from './product-entity';
import { PurchaseEntity } from './purchase-entity';
import { UserEntity } from './user-entity';
 /**
 * 
 *
 * @export
 * @interface ReviewEntity
 */
export interface ReviewEntity {

    /**
     * @type {string}
     * @memberof ReviewEntity
     */
    id?: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof ReviewEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof ReviewEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof ReviewEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof ReviewEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof ReviewEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {PurchaseEntity}
     * @memberof ReviewEntity
     */
    purchase?: PurchaseEntity;

    /**
     * @type {number}
     * @memberof ReviewEntity
     */
    rating?: number;

    /**
     * @type {string}
     * @memberof ReviewEntity
     */
    text?: string | null;

    /**
     * @type {UserEntity}
     * @memberof ReviewEntity
     */
    createdBy?: UserEntity;

    /**
     * @type {ProductEntity}
     * @memberof ReviewEntity
     */
    product?: ProductEntity;
}
