/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Stream
 */
export interface Stream {

    /**
     * @type {boolean}
     * @memberof Stream
     */
    canRead?: boolean;

    /**
     * @type {boolean}
     * @memberof Stream
     */
    canWrite?: boolean;

    /**
     * @type {boolean}
     * @memberof Stream
     */
    canSeek?: boolean;

    /**
     * @type {boolean}
     * @memberof Stream
     */
    canTimeout?: boolean;

    /**
     * @type {number}
     * @memberof Stream
     */
    length?: number;

    /**
     * @type {number}
     * @memberof Stream
     */
    position?: number;

    /**
     * @type {number}
     * @memberof Stream
     */
    readTimeout?: number;

    /**
     * @type {number}
     * @memberof Stream
     */
    writeTimeout?: number;
}
