/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { PaymentSystemEntity } from './payment-system-entity';
 /**
 * 
 *
 * @export
 * @interface TransactionProviderEntity
 */
export interface TransactionProviderEntity {

    /**
     * @type {string}
     * @memberof TransactionProviderEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof TransactionProviderEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof TransactionProviderEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof TransactionProviderEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof TransactionProviderEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof TransactionProviderEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof TransactionProviderEntity
     */
    name: string;

    /**
     * @type {number}
     * @memberof TransactionProviderEntity
     */
    fee: number;

    /**
     * @type {Array<PaymentSystemEntity>}
     * @memberof TransactionProviderEntity
     */
    systems: Array<PaymentSystemEntity>;
}
