/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateFileDto } from './create-file-dto';
 /**
 * 
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    userId: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    role?: UpdateUserDtoRoleEnum;

    /**
     * @type {CreateFileDto}
     * @memberof UpdateUserDto
     */
    avatar?: CreateFileDto;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    oldPassword?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    newPassword?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    telegramId?: string | null;

    /**
     * @type {boolean}
     * @memberof UpdateUserDto
     */
    blocked?: boolean | null;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateUserDtoRoleEnum {
    Other = 'Other',
    User = 'User',
    Seller = 'Seller',
    Moderator = 'Moderator',
    Admin = 'Admin',
    Owner = 'Owner',
    SuperAdmin = 'SuperAdmin'
}

