/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    productId: string;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof UpdateProductDto
     */
    price?: number | null;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof UpdateProductDto
     */
    attributes?: { [key: string]: string; } | null;

    /**
     * @type {Array<string>}
     * @memberof UpdateProductDto
     */
    images?: Array<string> | null;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    productStatus?: string | null;

    /**
     * @type {Array<string>}
     * @memberof UpdateProductDto
     */
    autoAnswers?: Array<string> | null;
}
