/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateFileDto } from './create-file-dto';
 /**
 * 
 *
 * @export
 * @interface UpdateGameDto
 */
export interface UpdateGameDto {

    /**
     * @type {string}
     * @memberof UpdateGameDto
     */
    gameId: string;

    /**
     * @type {string}
     * @memberof UpdateGameDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateGameDto
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof UpdateGameDto
     */
    type?: string | null;

    /**
     * @type {Array<string>}
     * @memberof UpdateGameDto
     */
    tags?: Array<string> | null;

    /**
     * @type {CreateFileDto}
     * @memberof UpdateGameDto
     */
    logo?: CreateFileDto;

    /**
     * @type {CreateFileDto}
     * @memberof UpdateGameDto
     */
    banner?: CreateFileDto;
}
