/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseEvent } from './base-event';
import { Money } from './money';
import { UserEntity } from './user-entity';
 /**
 * 
 *
 * @export
 * @interface WalletEntity
 */
export interface WalletEntity {

    /**
     * @type {string}
     * @memberof WalletEntity
     */
    id: string;

    /**
     * @type {Array<BaseEvent>}
     * @memberof WalletEntity
     */
    domainEvents?: Array<BaseEvent> | null;

    /**
     * @type {string}
     * @memberof WalletEntity
     */
    createdById?: string | null;

    /**
     * @type {Date}
     * @memberof WalletEntity
     */
    createdAt?: Date | null;

    /**
     * @type {string}
     * @memberof WalletEntity
     */
    lastModifiedById?: string | null;

    /**
     * @type {Date}
     * @memberof WalletEntity
     */
    lastModifiedAt?: Date | null;

    /**
     * @type {string}
     * @memberof WalletEntity
     */
    userId: string;

    /**
     * @type {UserEntity}
     * @memberof WalletEntity
     */
    user: UserEntity;

    /**
     * @type {string}
     * @memberof WalletEntity
     */
    currency: WalletEntityCurrencyEnum;

    /**
     * @type {Money}
     * @memberof WalletEntity
     */
    frozen: Money;

    /**
     * @type {Money}
     * @memberof WalletEntity
     */
    availableBalance: Money;

    /**
     * @type {Money}
     * @memberof WalletEntity
     */
    pendingIncome: Money;

    /**
     * @type {boolean}
     * @memberof WalletEntity
     */
    blocked: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum WalletEntityCurrencyEnum {
    RussianRuble = 'RussianRuble',
    Dollar = 'Dollar'
}

