/* tslint:disable */
/* eslint-disable */
/**
 * KarmaMarketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ReviewEntity } from '../models';
/**
 * ReviewControllersApi - axios parameter creator
 * @export
 */
export const ReviewControllersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewChatChatIdGet: async (chatId: string, start?: number, ends?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            if (chatId === null || chatId === undefined) {
                throw new RequiredError('chatId','Required parameter chatId was null or undefined when calling apiReviewChatChatIdGet.');
            }
            const localVarPath = `/api/review/chat/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (start !== undefined) {
                localVarQueryParameter['Start'] = start;
            }

            if (ends !== undefined) {
                localVarQueryParameter['Ends'] = ends;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewUserUserIdGet: async (userId: string, start?: number, ends?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling apiReviewUserUserIdGet.');
            }
            const localVarPath = `/api/review/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (start !== undefined) {
                localVarQueryParameter['Start'] = start;
            }

            if (ends !== undefined) {
                localVarQueryParameter['Ends'] = ends;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReviewControllersApi - functional programming interface
 * @export
 */
export const ReviewControllersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewChatChatIdGet(chatId: string, start?: number, ends?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ReviewEntity>>>> {
            const localVarAxiosArgs = await ReviewControllersApiAxiosParamCreator(configuration).apiReviewChatChatIdGet(chatId, start, ends, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewUserUserIdGet(userId: string, start?: number, ends?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ReviewEntity>>>> {
            const localVarAxiosArgs = await ReviewControllersApiAxiosParamCreator(configuration).apiReviewUserUserIdGet(userId, start, ends, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ReviewControllersApi - factory interface
 * @export
 */
export const ReviewControllersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewChatChatIdGet(chatId: string, start?: number, ends?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<ReviewEntity>>> {
            return ReviewControllersApiFp(configuration).apiReviewChatChatIdGet(chatId, start, ends, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} userId 
         * @param {number} [start] 
         * @param {number} [ends] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewUserUserIdGet(userId: string, start?: number, ends?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<ReviewEntity>>> {
            return ReviewControllersApiFp(configuration).apiReviewUserUserIdGet(userId, start, ends, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReviewControllersApi - object-oriented interface
 * @export
 * @class ReviewControllersApi
 * @extends {BaseAPI}
 */
export class ReviewControllersApi extends BaseAPI {
    /**
     * 
     * @param {string} chatId 
     * @param {number} [start] 
     * @param {number} [ends] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewControllersApi
     */
    public async apiReviewChatChatIdGet(chatId: string, start?: number, ends?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<ReviewEntity>>> {
        return ReviewControllersApiFp(this.configuration).apiReviewChatChatIdGet(chatId, start, ends, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} userId 
     * @param {number} [start] 
     * @param {number} [ends] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewControllersApi
     */
    public async apiReviewUserUserIdGet(userId: string, start?: number, ends?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<ReviewEntity>>> {
        return ReviewControllersApiFp(this.configuration).apiReviewUserUserIdGet(userId, start, ends, options).then((request) => request(this.axios, this.basePath));
    }
}
